<?php

namespace Database\Factories;

use App\Models\Conversation;
use App\Models\Enums\MessageStatus;
use App\Models\Message;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Message>
 */
class MessageFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'conversation_id' => Conversation::factory(),
            'sender_type' => 'customer',
            'sender_id' => null,
            'content_type' => 'text',
            'content_text' => fake()->sentence(),
            'status' => MessageStatus::Sent,
            'ai_generated' => false,
        ];
    }

    /**
     * Indicate that the message was sent by a customer (inbound).
     */
    public function incoming(): static
    {
        return $this->state(fn (): array => ['sender_type' => 'customer']);
    }

    /**
     * Indicate that the message was sent by a human agent (outbound).
     */
    public function outgoing(): static
    {
        return $this->state(fn (): array => [
            'sender_type' => 'agent',
            'sender_id' => User::factory(),
        ]);
    }

    /**
     * Indicate that the message was generated by the AI assistant.
     */
    public function aiGenerated(): static
    {
        return $this->state(fn (): array => [
            'sender_type' => 'bot',
            'ai_generated' => true,
        ]);
    }

    /**
     * Indicate that the message reached the `delivered` step.
     */
    public function delivered(): static
    {
        return $this->state(fn (): array => ['status' => MessageStatus::Delivered]);
    }

    /**
     * Indicate that the message reached the `read` step.
     */
    public function read(): static
    {
        return $this->state(fn (): array => ['status' => MessageStatus::Read]);
    }

    /**
     * Indicate that the message failed delivery.
     */
    public function failed(): static
    {
        return $this->state(fn (): array => ['status' => MessageStatus::Failed]);
    }
}
